//
// Generated file, do not edit! Created by opp_msgc 4.5 from OrionPackets.msg.
//

#ifndef _ORIONPACKETS_M_H_
#define _ORIONPACKETS_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0405
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "IPvXAddress.h"
#include "simtime_t.h"
// }}



/**
 * Enum generated from <tt>OrionPackets.msg</tt> by opp_msgc.
 * <pre>
 * enum OrionPacketType
 * {
 *     QUERY = 1;
 *     RESPONSE = 2;
 *     DATA_REQUEST = 3;
 *     DATA_REPLY = 4;
 *     DATA_REQUEST_ACK = 5;
 * };
 * </pre>
 */
enum OrionPacketType {
    QUERY = 1,
    RESPONSE = 2,
    DATA_REQUEST = 3,
    DATA_REPLY = 4,
    DATA_REQUEST_ACK = 5
};

/**
 * Class generated from <tt>OrionPackets.msg</tt> by opp_msgc.
 * <pre>
 * packet OrionPacket extends cPacket
 * {
 *     unsigned int packetType;
 *     IPvXAddress DST;
 *     IPvXAddress SRC;
 *     IPvXAddress LastNode;
 *     unsigned int SEQ;
 *     string filename;
 * }
 * </pre>
 */
class OrionPacket : public ::cPacket
{
  protected:
    unsigned int packetType_var;
    IPvXAddress DST_var;
    IPvXAddress SRC_var;
    IPvXAddress LastNode_var;
    unsigned int SEQ_var;
    opp_string filename_var;

  private:
    void copy(const OrionPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const OrionPacket&);

  public:
    OrionPacket(const char *name=NULL, int kind=0);
    OrionPacket(const OrionPacket& other);
    virtual ~OrionPacket();
    OrionPacket& operator=(const OrionPacket& other);
    virtual OrionPacket *dup() const {return new OrionPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned int getPacketType() const;
    virtual void setPacketType(unsigned int packetType);
    virtual IPvXAddress& getDST();
    virtual const IPvXAddress& getDST() const {return const_cast<OrionPacket*>(this)->getDST();}
    virtual void setDST(const IPvXAddress& DST);
    virtual IPvXAddress& getSRC();
    virtual const IPvXAddress& getSRC() const {return const_cast<OrionPacket*>(this)->getSRC();}
    virtual void setSRC(const IPvXAddress& SRC);
    virtual IPvXAddress& getLastNode();
    virtual const IPvXAddress& getLastNode() const {return const_cast<OrionPacket*>(this)->getLastNode();}
    virtual void setLastNode(const IPvXAddress& LastNode);
    virtual unsigned int getSEQ() const;
    virtual void setSEQ(unsigned int SEQ);
    virtual const char * getFilename() const;
    virtual void setFilename(const char * filename);
};

inline void doPacking(cCommBuffer *b, OrionPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, OrionPacket& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>OrionPackets.msg</tt> by opp_msgc.
 * <pre>
 * class OrionQueryPacket extends OrionPacket
 * {
 *     unsigned int packetType = QUERY;
 * 
 *  }
 * </pre>
 */
class OrionQueryPacket : public ::OrionPacket
{
  protected:
    unsigned int packetType_var;

  private:
    void copy(const OrionQueryPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const OrionQueryPacket&);

  public:
    OrionQueryPacket(const char *name=NULL);
    OrionQueryPacket(const OrionQueryPacket& other);
    virtual ~OrionQueryPacket();
    OrionQueryPacket& operator=(const OrionQueryPacket& other);
    virtual OrionQueryPacket *dup() const {return new OrionQueryPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned int getPacketType() const;
    virtual void setPacketType(unsigned int packetType);
};

inline void doPacking(cCommBuffer *b, OrionQueryPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, OrionQueryPacket& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>OrionPackets.msg</tt> by opp_msgc.
 * <pre>
 * class OrionResponsePacket extends OrionPacket
 * {
 *     unsigned int packetType = RESPONSE;
 *     unsigned int hopcount;
 *  }
 * </pre>
 */
class OrionResponsePacket : public ::OrionPacket
{
  protected:
    unsigned int packetType_var;
    unsigned int hopcount_var;

  private:
    void copy(const OrionResponsePacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const OrionResponsePacket&);

  public:
    OrionResponsePacket(const char *name=NULL);
    OrionResponsePacket(const OrionResponsePacket& other);
    virtual ~OrionResponsePacket();
    OrionResponsePacket& operator=(const OrionResponsePacket& other);
    virtual OrionResponsePacket *dup() const {return new OrionResponsePacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned int getPacketType() const;
    virtual void setPacketType(unsigned int packetType);
    virtual unsigned int getHopcount() const;
    virtual void setHopcount(unsigned int hopcount);
};

inline void doPacking(cCommBuffer *b, OrionResponsePacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, OrionResponsePacket& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>OrionPackets.msg</tt> by opp_msgc.
 * <pre>
 * class OrionDataReqPacket extends OrionPacket
 * {
 *     unsigned int packetType = DATA_REQUEST;
 *     unsigned int retries;
 *    	unsigned int block;
 *    	 string bid;
 * }
 * </pre>
 */
class OrionDataReqPacket : public ::OrionPacket
{
  protected:
    unsigned int packetType_var;
    unsigned int retries_var;
    unsigned int block_var;
    opp_string bid_var;

  private:
    void copy(const OrionDataReqPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const OrionDataReqPacket&);

  public:
    OrionDataReqPacket(const char *name=NULL);
    OrionDataReqPacket(const OrionDataReqPacket& other);
    virtual ~OrionDataReqPacket();
    OrionDataReqPacket& operator=(const OrionDataReqPacket& other);
    virtual OrionDataReqPacket *dup() const {return new OrionDataReqPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned int getPacketType() const;
    virtual void setPacketType(unsigned int packetType);
    virtual unsigned int getRetries() const;
    virtual void setRetries(unsigned int retries);
    virtual unsigned int getBlock() const;
    virtual void setBlock(unsigned int block);
    virtual const char * getBid() const;
    virtual void setBid(const char * bid);
};

inline void doPacking(cCommBuffer *b, OrionDataReqPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, OrionDataReqPacket& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>OrionPackets.msg</tt> by opp_msgc.
 * <pre>
 * class OrionDataAckPacket extends OrionPacket
 * {
 *     unsigned int packetType = DATA_REQUEST_ACK;
 *     unsigned int retries;
 *    	unsigned int block;
 *    	string bid;
 * }
 * </pre>
 */
class OrionDataAckPacket : public ::OrionPacket
{
  protected:
    unsigned int packetType_var;
    unsigned int retries_var;
    unsigned int block_var;
    opp_string bid_var;

  private:
    void copy(const OrionDataAckPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const OrionDataAckPacket&);

  public:
    OrionDataAckPacket(const char *name=NULL);
    OrionDataAckPacket(const OrionDataAckPacket& other);
    virtual ~OrionDataAckPacket();
    OrionDataAckPacket& operator=(const OrionDataAckPacket& other);
    virtual OrionDataAckPacket *dup() const {return new OrionDataAckPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned int getPacketType() const;
    virtual void setPacketType(unsigned int packetType);
    virtual unsigned int getRetries() const;
    virtual void setRetries(unsigned int retries);
    virtual unsigned int getBlock() const;
    virtual void setBlock(unsigned int block);
    virtual const char * getBid() const;
    virtual void setBid(const char * bid);
};

inline void doPacking(cCommBuffer *b, OrionDataAckPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, OrionDataAckPacket& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>OrionPackets.msg</tt> by opp_msgc.
 * <pre>
 * class OrionDataRepPacket extends OrionPacket
 * {
 *    
 *     unsigned int packetType = DATA_REPLY;
 *     unsigned int block;
 *     string bid;
 * }
 * </pre>
 */
class OrionDataRepPacket : public ::OrionPacket
{
  protected:
    unsigned int packetType_var;
    unsigned int block_var;
    opp_string bid_var;

  private:
    void copy(const OrionDataRepPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const OrionDataRepPacket&);

  public:
    OrionDataRepPacket(const char *name=NULL);
    OrionDataRepPacket(const OrionDataRepPacket& other);
    virtual ~OrionDataRepPacket();
    OrionDataRepPacket& operator=(const OrionDataRepPacket& other);
    virtual OrionDataRepPacket *dup() const {return new OrionDataRepPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned int getPacketType() const;
    virtual void setPacketType(unsigned int packetType);
    virtual unsigned int getBlock() const;
    virtual void setBlock(unsigned int block);
    virtual const char * getBid() const;
    virtual void setBid(const char * bid);
};

inline void doPacking(cCommBuffer *b, OrionDataRepPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, OrionDataRepPacket& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>OrionPackets.msg</tt> by opp_msgc.
 * <pre>
 * message WaitForReq extends cMessage
 * {
 *     string filename;
 *     string bid;
 *     unsigned int block;
 * }
 * </pre>
 */
class WaitForReq : public ::cMessage
{
  protected:
    opp_string filename_var;
    opp_string bid_var;
    unsigned int block_var;

  private:
    void copy(const WaitForReq& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const WaitForReq&);

  public:
    WaitForReq(const char *name=NULL, int kind=0);
    WaitForReq(const WaitForReq& other);
    virtual ~WaitForReq();
    WaitForReq& operator=(const WaitForReq& other);
    virtual WaitForReq *dup() const {return new WaitForReq(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getFilename() const;
    virtual void setFilename(const char * filename);
    virtual const char * getBid() const;
    virtual void setBid(const char * bid);
    virtual unsigned int getBlock() const;
    virtual void setBlock(unsigned int block);
};

inline void doPacking(cCommBuffer *b, WaitForReq& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, WaitForReq& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>OrionPackets.msg</tt> by opp_msgc.
 * <pre>
 * message ReqBlockTimer extends cMessage
 * {
 *     string filename;
 * }
 * </pre>
 */
class ReqBlockTimer : public ::cMessage
{
  protected:
    opp_string filename_var;

  private:
    void copy(const ReqBlockTimer& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ReqBlockTimer&);

  public:
    ReqBlockTimer(const char *name=NULL, int kind=0);
    ReqBlockTimer(const ReqBlockTimer& other);
    virtual ~ReqBlockTimer();
    ReqBlockTimer& operator=(const ReqBlockTimer& other);
    virtual ReqBlockTimer *dup() const {return new ReqBlockTimer(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getFilename() const;
    virtual void setFilename(const char * filename);
};

inline void doPacking(cCommBuffer *b, ReqBlockTimer& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, ReqBlockTimer& obj) {obj.parsimUnpack(b);}


#endif // _ORIONPACKETS_M_H_
